In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime
import dataframe_image as dfi

In [2]:
# reading the data
df = pd.read_csv('./data/SAP Stock Purchases - Felipe Rosa Renck - 2020.csv', delimiter=';', header=0, index_col=0, parse_dates=True, squeeze=True)
df2 = pd.read_csv('./data/Stock_Price_BRL 2016-2021.csv', header=0, index_col=0, parse_dates=True, squeeze=True)

df = df[df["Activity"].str.contains("Match") == False]
print(df.shape)

df

(12, 3)

            Activity Purchase/Sell price  Quantity
Date
2020-12-08  Purchase            € 101,26  0,570108
2020-11-09  Purchase            € 100,87  0,519668
2020-10-09  Purchase            € 132,58  0,403157
2020-09-09  Purchase            € 135,40  0,404355
2020-08-07  Purchase            € 136,78  0,423243
2020-07-09  Purchase            € 138,35  0,419152
2020-06-05  Purchase            € 115,61  0,030619
2020-05-07  Purchase            € 107,61  0,562425
2020-04-09  Purchase            € 107,61  0,577845
2020-03-06  Purchase            € 107,18  0,671676
2020-02-07  Purchase            € 124,23  0,605015
2020-01-09  Purchase            € 122,93  0,627675

In [4]:
#Filter df2 to only the year 2020
df2_2020 = df2['2020']
df2_2020['Close_Stock_EUR'] = df2_2020['Close_Stock(EUR)']
df2_2020 = df2_2020.rename(columns={'Close_Stock(BRL)': 'Close_Stock_BRL'})
df2_2020

C:\Users\I514609\AppData\Local\Temp/ipykernel_11952/1131512052.py:2: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  df2_2020 = df2['2020']
C:\Users\I514609\AppData\Local\Temp/ipykernel_11952/1131512052.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2_2020['Close_Stock_EUR'] = df2_2020['Close_Stock(EUR)']

            Close_Stock(EUR)  Close_EUR  Close_Stock_BRL  Close_Stock_EUR
Date
2020-01-02        122.000000     4.4883       547.572600       122.000000
2020-01-03        120.459999     4.4920       541.106316       120.459999
2020-01-06        119.559998     4.5338       542.061119       119.559998
2020-01-07        120.099998     4.5434       545.662331       120.099998
2020-01-08        120.820000     4.5322       547.580404       120.820000
...                      ...        ...              ...              ...
2020-12-22        103.620003     6.2643       649.106785       103.620003
2020-12-23        103.760002     6.2839       652.017477       103.760002
2020-12-28        105.260002     6.3372       667.053685       105.260002
2020-12-29        106.800003     6.4080       684.374419       106.800003
2020-12-30        107.220001     6.3802       684.085050       107.220001

[254 rows x 4 columns]

In [7]:
# Get Subset by month
df_january = df2_2020[df2_2020.index.month == 1]
df_february = df2_2020[df2_2020.index.month == 2]
df_march = df2_2020[df2_2020.index.month == 3]
df_april = df2_2020[df2_2020.index.month == 4]
df_may = df2_2020[df2_2020.index.month == 5]
df_june = df2_2020[df2_2020.index.month == 6]
df_july = df2_2020[df2_2020.index.month == 7]
df_august = df2_2020[df2_2020.index.month == 8]
df_september = df2_2020[df2_2020.index.month == 9]
df_october = df2_2020[df2_2020.index.month == 10]
df_november = df2_2020[df2_2020.index.month == 11]
df_december = df2_2020[df2_2020.index.month == 12]

In [9]:
# Print max values by each month
#print(df_january[df_january['Close_Stock_BRL']==df_january['Close_Stock_BRL'].max()])
#print(df_february[df_february['Close_Stock_BRL']==df_february['Close_Stock_BRL'].max()])
#print(df_march[df_march['Close_Stock_BRL']==df_march['Close_Stock_BRL'].max()])
#print(df_april[df_april['Close_Stock_BRL']==df_april['Close_Stock_BRL'].max()])
#print(df_may[df_may['Close_Stock_BRL']==df_may['Close_Stock_BRL'].max()])
#print(df_june[df_june['Close_Stock_BRL']==df_june['Close_Stock_BRL'].max()])
#print(df_july[df_july['Close_Stock_BRL']==df_july['Close_Stock_BRL'].max()])
print(df_august[df_august['Close_Stock_BRL']==df_august['Close_Stock_BRL'].max()])
print(df_september[df_september['Close_Stock_BRL']==df_september['Close_Stock_BRL'].max()])
print(df_october[df_october['Close_Stock_BRL']==df_october['Close_Stock_BRL'].max()])
print(df_november[df_november['Close_Stock_BRL']==df_november['Close_Stock_BRL'].max()])
print(df_december[df_december['Close_Stock_BRL']==df_december['Close_Stock_BRL'].max()])

            Close_Stock(EUR)  Close_EUR  Close_Stock_BRL  Close_Stock_EUR
Date
2020-08-27        140.360001     6.6354       931.344751       140.360001
            Close_Stock(EUR)  Close_EUR  Close_Stock_BRL  Close_Stock_EUR
Date
2020-09-02             141.5     6.4329        910.25535            141.5
            Close_Stock(EUR)  Close_EUR  Close_Stock_BRL  Close_Stock_EUR
Date
2020-10-05        132.399994     6.6539        880.97632       132.399994
            Close_Stock(EUR)  Close_EUR  Close_Stock_BRL  Close_Stock_EUR
Date
2020-11-04             96.75     6.7662        654.62985            96.75
            Close_Stock(EUR)  Close_EUR  Close_Stock_BRL  Close_Stock_EUR
Date
2020-12-29        106.800003      6.408       684.374419       106.800003

In [ ]:
print(df_january[df_january['Close_Stock_EUR']==df_january['Close_Stock_EUR'].max()])
print(df_february[df_february['Close_Stock_EUR']==df_february['Close_Stock_EUR'].max()])
print(df_march[df_march['Close_Stock_EUR']==df_march['Close_Stock_EUR'].max()])
print(df_april[df_april['Close_Stock_EUR']==df_april['Close_Stock_EUR'].max()])
print(df_may[df_may['Close_Stock_EUR']==df_may['Close_Stock_EUR'].max()])
print(df_june[df_june['Close_Stock_EUR']==df_june['Close_Stock_EUR'].max()])
print(df_july[df_july['Close_Stock_EUR']==df_july['Close_Stock_EUR'].max()])
print(df_august[df_august['Close_Stock_EUR']==df_august['Close_Stock_EUR'].max()])
print(df_september[df_september['Close_Stock_EUR']==df_september['Close_Stock_EUR'].max()])
print(df_october[df_october['Close_Stock_EUR']==df_october['Close_Stock_EUR'].max()])
print(df_november[df_november['Close_Stock_EUR']==df_november['Close_Stock_EUR'].max()])
print(df_december[df_december['Close_Stock_EUR']==df_december['Close_Stock_EUR'].max()])